<h1>Ajouter un nouveau logement</h1>
<form method="POST">
    <label>Prix : <input type="number" name="price" required></label>
    <label>Surface : <input type="number" name="surface" required></label>
    <label>Description : <textarea name="description" required></textarea></label>
    <label>Capacité : <input type="number" name="capacity" required></label>
    <label>Type de logement : <input type="text" name="id_type" required></label>
    <label>Adresse : <input type="text" name="id_address" required></label>
    <button type="submit">Ajouter</button>
</form>