<h1>Ajouter un logement</h1>
<form method="POST">
    <label>Prix : <input type="number" step="0.01" name="price" required></label>
    <label>Surface : <input type="number" name="surface" required></label>
    <label>Description : <textarea name="description" required></textarea></label>
    <label>Capacité : <input type="number" name="capacity" required></label>
    <label>ID Propriétaire : <input type="number" name="id_owner" required></label>
    <label>ID Type : <input type="number" name="id_type" required></label>
    <label>ID Adresse : <input type="number" name="id_address" required></label>
    <button type="submit">Ajouter</button>
</form>