<h1>Inscription</h1>
<form method="POST">
    <label>Email : <input type="email" name="email" required></label>
    <label>Mot de passe : <input type="password" name="password" required></label>
    <label>Nom : <input type="text" name="lastname" required></label>
    <label>Prénom : <input type="text" name="firstname" required></label>
    <label>Téléphone : <input type="text" name="phone_number"></label>
    <button type="submit">S'inscrire</button>
</form>